media:
  - name: podcasts
    label: Podcast Images
    input: src/images/resources/podcasts
    output: /podcasts
    extensions: [ webp ]
  - name: tvshows
    label: TV Show Images
    input: src/images/resources/tvshows
    output: /tvshows
    extensions: [ webp ]
  - name: freebies
    label: Freebie Images
    input: src/assets/freebies
    output: /freebies
    extensions: [ webp, png, jpg, jpeg ]

content:
  - name: podcasts
    label: Podcasts
    type: collection
    path: src/data/resources/podcasts
    format: yaml-frontmatter
    subfolders: false
    view:
      fields: [ title, theme, link ]
      primary: title
      sort: [ title ]
      default:
        search: ''
        sort: title
        order: asc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: shortDescription
        label: Short Description
        type: text
      - name: longDescription
        label: Long Description
        type: text
      - name: theme
        label: Theme
        type: string
      - name: image
        label: Image
        type: image
        options:
          media: podcasts
          extensions: [ webp ]
      - name: link
        label: Link
        type: string
  - name: tvshows
    label: TV Shows
    type: collection
    path: src/data/resources/tvshows
    format: yaml-frontmatter
    subfolders: false
    view:
      fields: [ title, theme, link ]
      primary: title
      sort: [ title ]
      default:
        search: ''
        sort: title
        order: asc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: longDescription
        label: Long Description
        type: text
      - name: theme
        label: Theme
        type: string
      - name: image
        label: Image
        type: image
        options:
          media: tvshows
          extensions: [ webp ]
      - name: link
        label: Link
        type: string
  - name: freebies
    label: Freebies
    type: collection
    path: src/data/freebies
    format: yaml-frontmatter
    subfolders: false
    view:
      fields: [ title, slug ]
      primary: title
      sort: [ title ]
      default:
        search: ''
        sort: title
        order: asc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitle
        label: Subtitle
        type: text
      - name: description
        label: Description
        type: text
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
      - name: buttonText
        label: Button Text
        type: string
      - name: resourceURL
        label: Resource URL
        type: string
        required: true
      - name: image
        label: Image
        type: image
        options:
          media: freebies
          extensions: [ webp, png, jpg, jpeg ]
      - name: metaTitle
        label: Meta Title
        type: string
      - name: metaDescription
        label: Meta Description
        type: text
