media:
  - name: podcasts
    label: Podcast Images
    input: src/images/resources/podcasts
    output: /podcasts
    extensions: [ webp ]
  - name: tvshows
    label: TV Show Images
    input: src/images/resources/tvshows
    output: /tvshows
    extensions: [ webp ]

content:
  - name: podcasts
    label: Podcasts
    type: collection
    path: src/data/resources/podcasts
    format: yaml-frontmatter
    subfolders: false
    view:
      fields: [ title, theme, link ]
      primary: title
      sort: [ title ]
      default:
        search: ''
        sort: title
        order: asc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: shortDescription
        label: Short Description
        type: text
      - name: longDescription
        label: Long Description
        type: text
      - name: theme
        label: Theme
        type: string
      - name: image
        label: Image
        type: image
        options:
          media: podcasts
          extensions: [ webp ]
      - name: link
        label: Link
        type: string
  - name: tvshows
    label: TV Shows
    type: collection
    path: src/data/resources/tvshows
    format: yaml-frontmatter
    subfolders: false
    view:
      fields: [ title, theme, link ]
      primary: title
      sort: [ title ]
      default:
        search: ''
        sort: title
        order: asc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: longDescription
        label: Long Description
        type: text
      - name: theme
        label: Theme
        type: string
      - name: image
        label: Image
        type: image
        options:
          media: tvshows
          extensions: [ webp ]
      - name: link
        label: Link
        type: string
